### ISSUE TITLE
Existence of indoor positioning and triangulation function

### ISSUE THREAD

**Issue by soseazi** [Jason-Gew/BLE-Beacon-Tracking-System#14]
Firstly, appreciate your great work. 
I am new to this field and was a bit lost with the concept of BLE indoor positioning but your work has given me some inspiration.

Question is, does your code also provide indoor positioning function? 
On the readme document, you mentioned "For indoor positioning and triangulation, multiple clients (hardware, at least 3+) should be placed in correct location according to reasonable coordination."
If not yet provided, any direction or thoughts to get through? it would be greatly appreciated.

Also, have you tested with Rpi3 or Rpi4? What's the error range of between the ground-truth(actual) beacon position and the estimated position of the beacon? within 30cm? or less?

Will look forward to your reply.

Thanks.

**Comment by Jason-Gew** [comment]
> Hi,

First of all, thank you for reading the code repository. This is a client-side code and has been tested on Raspberry Pi 3 (Should work with Pi4 as well).

It provides the capability to measure the RSSI with corresponding information from your BLE beacons and send to server-side based on MQTT protocol. On the server side, you will need to use a **triangulation algorithm** to achieve indoor positioning (my server side code has not been released yet). Due to differences in interior buildings and maps, you have to figure out the correct error redundancy (an inevitable step when I deploy to different buildings).

Usually a trade off between accuracy and latency need to be considered. In my previous situations, with 30s delay, the miss-match range can be less than 50CM average in multiple rooms.
